---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/pmacik-testing/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-fix/KONFLUX-2096_PR-714-vwjy
