---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/pmacik-testing/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-bump-pipeilne-perf-settings-szam
