---
- op: replace
  path: /spec/pipeline/performance/threads-per-controller
  # default upstream setting
  # value: 2
  # upstream large scale env recommendation
  value: 32
- op: replace
  path: /spec/pipeline/performance/kube-api-qps
  # default upstream setting
  # value: 5.0
  # upstream large scale env recommendation
  value: 50
- op: replace
  path: /spec/pipeline/performance/kube-api-burst
  # default upstream setting
  #value: 10
  # upstream large scale env recommendation
  value: 50
- op: add
  path: /spec/pipeline/default-pod-template
  # Add a topology spread constraint to distribute the pods
  value: |
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/managed-by: tekton-pipelines
