apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Skip applying the Tekton/PaC operands while the Tekton/PaC operator is being installed.
# See more information about this option, here: 
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types 
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - git::https://github.com/openshift-pipelines/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service?ref=3233088aa6376cb04689c8ba7b96246f33a4197b
  - git::https://github.com/openshift-pipelines/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service-storage?ref=3233088aa6376cb04689c8ba7b96246f33a4197b
  - bundleconfigmap-kvs.yaml

patches:
#  - path: scale-down-exporter.yaml
#    target:
#      kind: Deployment
#      name: pipeline-metrics-exporter
#      namespace: openshift-pipelines
  - target:
      kind: Subscription
      group: operators.coreos.com
      version: v1alpha1
      name: openshift-pipelines-operator
      namespace: openshift-operators
    path: use-poc-images.yaml
  - path: update-tekton-config-performance.yaml
    target:
      kind: TektonConfig
      name: config
