apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Skip applying the Tekton/PaC operands while the Tekton/PaC operator is being installed.
# See more information about this option, here:
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - https://github.com/gabemontero/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service?ref=test-latest-grpc-deep-dive
  - https://github.com/gabemontero/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service-storage?ref=test-latest-grpc-deep-dive
  - ../base/rbac

patches:
  - path: chains-tekton-config-patches.yaml
    target:
      kind: TektonConfig
      name: config
  - path: metrics-exporter-trace.yaml
    target:
      kind: Deployment
      name: pipeline-metrics-exporter
      namespace: openshift-pipelines
#  - path: scale-down-exporter.yaml
#    target:
#      kind: Deployment
#      name: pipeline-metrics-exporter
#      namespace: openshift-pipelines
  - path: update-tekton-config-performance.yaml
    target:
      kind: TektonConfig
      name: config
  - path: bump-results-watcher-replicas.yaml
    target:
      kind: Deployment
      namespace: tekton-results
      name: tekton-results-watcher
  - path: update-results-watcher-args.yaml
    target:
      kind: Deployment
      namespace: tekton-results
      name: tekton-results-watcher
  - path: reduce-watcher-cpu-mem-reqs.yaml
    target:
      kind: Deployment
      namespace: tekton-results
      name: tekton-results-watcher
  - path: enable-step-actions.yaml
    target:
      kind: TektonConfig
      name: config
#  - path: update-results-watcher-performance.yaml
#    target:
#      kind: Deployment
#      namespace: tekton-results
#      name: tekton-results-watcher