apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Skip applying the Tekton/PaC operands while the Tekton/PaC operator is being installed.
# See more information about this option, here: 
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#skip-dry-run-for-new-custom-resources-types 
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - https://github.com/pmacik/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service?ref=425de42b6c2ec0da91875fb3e613d565aae8fe02
  - https://github.com/pmacik/pipeline-service.git/developer/openshift/gitops/argocd/pipeline-service-storage?ref=425de42b6c2ec0da91875fb3e613d565aae8fe02
  - ../base/rbac

patches:
  - path: metrics-exporter-trace.yaml
    target:
      kind: Deployment
      name: pipeline-metrics-exporter
      namespace: openshift-pipelines
#  - path: scale-down-exporter.yaml
#    target:
#      kind: Deployment
#      name: pipeline-metrics-exporter
#      namespace: openshift-pipelines
  - path: update-tekton-config-performance.yaml
    target:
      kind: TektonConfig
      name: config
