---
- op: replace
  path: /spec/pipeline/performance/threads-per-controller
  value: 2
- op: replace
  path: /spec/pipeline/performance/kube-api-qps
  value: 5
- op: replace
  path: /spec/pipeline/performance/kube-api-burst
  value: 10
