---
- op: replace
  path: /spec/pipeline/performance/threads-per-controller
  value: 32
- op: replace
  path: /spec/pipeline/performance/kube-api-qps
  value: 50
- op: replace
  path: /spec/pipeline/performance/kube-api-burst
  value: 50
