---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-watcher
spec:
  template:
    spec:
      containers:
        - name: watcher
          args:
            [
              "-api_addr",
              "tekton-results-api-service.tekton-results.svc.cluster.local:8080",
              "-auth_mode",
              "token",
              "-check_owner=false",
              "-completed_run_grace_period=2h",
              "-threadiness",
              "50",
              "-qps",
              "50",
              "-burst",
              "100",
              "-update_log_timeout",
              "2m",
            ]
