---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  config:
    env:
      - name: IMAGE_PIPELINES_CONTROLLER
        value: quay.io/gabemontero/resolvers-ff86b24f130c42b88983d3c13993056d